#██╗   ██╗ █████╗ ███╗   ██╗███████╗███████╗██╗  ██╗██████╗  ██████╗ 
#██║   ██║██╔══██╗████╗  ██║██╔════╝██╔════╝██║  ██║╚════██╗██╔═████╗
#██║   ██║███████║██╔██╗ ██║█████╗  ███████╗███████║ █████╔╝██║██╔██║
#╚██╗ ██╔╝██╔══██║██║╚██╗██║██╔══╝  ╚════██║╚════██║ ╚═══██╗████╔╝██║
# ╚████╔╝ ██║  ██║██║ ╚████║███████╗███████║     ██║██████╔╝╚██████╔╝
#  ╚═══╝  ╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝╚══════╝     ╚═╝╚═════╝  ╚═════╝ 
# Pterodactyl Image created by vanes430
# syntax=docker/dockerfile:1.5
FROM --platform=$TARGETOS/$TARGETARCH azul/zulu-openjdk-debian:17-latest

LABEL author="vanes430" \
      maintainer="admin@vanes430.my.id" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.source="https://github.com/vanes430/protection" \
      org.opencontainers.image.description="Pterodactyl Image created by vanes430"

RUN apt-get update && apt-get install -y \
        fontconfig \
        iproute2 \
        openssl \
        sqlite3 \
        tar \
        passwd \
        udev \
        fonts-noto-color-emoji \
        fonts-noto \
        fonts-dejavu-core \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && useradd -m -d /home/container container

ENV LANG="en_US.UTF-8" \
    LANGUAGE="en_US:en" \
    LC_ALL="en_US.UTF-8"

USER container
ENV USER="container" \
    HOME="/home/container"
WORKDIR /home/container

COPY ../entrypoint /entrypoint
RUN chmod +x /entrypoint

ENTRYPOINT ["/entrypoint"]
