name: cleanup
on:
  workflow_run:
    workflows: ["docker build"]   # nama workflow pertama
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Delete all untagged and non-latest versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: protection
          delete-only-untagged-versions: true
